modLoader="javafml"
loaderVersion="[41,)"
license="GNU LGPLv3"
[[mods]]
modId="propellerhats"
version="${file.jarVersion}"
displayName="Propeller Hats"
description='''
Adds propeller hats used for flying.
'''
[[dependencies.propellerhats]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.propellerhats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"