modLoader="javafml"
loaderVersion="[38,)"
license="GNU LGPLv3"
[[mods]]
modId="propellerhats"
version="${file.jarVersion}"
displayName="Propeller Hats"
description='''
Adds propeller hats used for flying.
'''
[[dependencies.propellerhats]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.propellerhats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"