modLoader="javafml"
loaderVersion="[46,)"
license="GNU LGPLv3"
[[mods]]
modId="propellerhats"
version="${file.jarVersion}"
displayName="Propeller Hats"
description='''
Adds propeller hats used for flying.
'''
[[dependencies.propellerhats]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.propellerhats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"